services:
  barracuda-thruster-output-controller:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    image: barracuda-manipulator
    container_name: barracuda-manipulator
    tty: true
    network_mode: host
    restart: "always"
    volumes:
      # - $HOME/.gitconfig:/root/.gitconfig:ro
      - $HOME/.ssh:/root/.ssh
    
